[build]
  publish = "build"
  command = "npm run build"

[[redirects]]
  from = "/#/*"
  to = "/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/index.html#/*"
  to = "/:splat"
  status = 301
  force = true